name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Verify Python environment
        run: |
          which python
          python --version
          pip list | grep Django || echo "Django no está instalado"
        shell: bash

      - name: Run Tests
        run: |
          source venv/bin/activate
          MOZ_HEADLESS=1 python manage.py test
        shell: bash


